import express from 'express';
import customerStoryRoutes from './customerStory.js';
import certificate from './certificate.js';
import faqRoutes from './faq.js';
import settingRoutes from './setting.js';
import aboutUsRoutes from './aboutUs.js';
import sliderRoutes from './slider.js';
import policyRoutes from './policies.js';
import enquiryRoutes from './enquiryRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import blogRoutes from './blogRoutes.js';
import pageMetaRoutes from './pageMetaRoutes.js';
import additionalRoutes from './additionalRoutes.js';
import packageRoutes from './packageRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import moreTrekRoutes from './moreTrekRoutes.js';
import contactRoutes from './contactRoutes.js';
import blogCategoryRoutes from './blogCategoryRoutes.js';
import blogTagRoutes from './blogTagRoutes.js';
import aboutUsSectionRoutes from './aboutUsSectionRoutes.js';
import packageEnquiryRoutes from './packageEnquiryRoutes.js';
import announcementRoutes from './announcement.js';
const router = express.Router();
// router.use('/roles', rolesRouter);


// Manager routes
// router.use('/managers', managersRouter);
router.use('/sliders', sliderRoutes);
router.use('/announcements', announcementRoutes);
router.use('/customer-stories', customerStoryRoutes);
router.use('/certificates', certificate);
router.use('/faqs', faqRoutes);
router.use('/settings', settingRoutes);
router.use('/about-us', aboutUsRoutes);
router.use('/about-us-sections', aboutUsSectionRoutes);
router.use('/policies', policyRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/bookings', bookingRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/blogs', blogRoutes);
router.use('/blog-categories', blogCategoryRoutes);
router.use('/blog-tags', blogTagRoutes);
router.use('/page-meta', pageMetaRoutes);
router.use('/additionals', additionalRoutes);
router.use('/packages', packageRoutes);
router.use('/categories', categoryRoutes);
router.use('/more-treks', moreTrekRoutes);
router.use('/contacts', contactRoutes);
router.use('/package-enquiries', packageEnquiryRoutes);
export default router;
